package entidades;
// Generated 04/06/2018 13:52:03 by Hibernate Tools 4.3.1



/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer idCompra;
     private Fornecedor fornecedor;
     private Produto produto;
     private Usuario usuario;
     private Double precoUnitario;
     private Integer quantidade;
     private Double desconto;
     private Double total;

    public Compra() {
    }

    public Compra(Fornecedor fornecedor, Produto produto, Usuario usuario, Double precoUnitario, Integer quantidade, Double desconto, Double total) {
       this.fornecedor = fornecedor;
       this.produto = produto;
       this.usuario = usuario;
       this.precoUnitario = precoUnitario;
       this.quantidade = quantidade;
       this.desconto = desconto;
       this.total = total;
    }
   
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Double getPrecoUnitario() {
        return this.precoUnitario;
    }
    
    public void setPrecoUnitario(Double precoUnitario) {
        this.precoUnitario = precoUnitario;
    }
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }
    public Double getDesconto() {
        return this.desconto;
    }
    
    public void setDesconto(Double desconto) {
        this.desconto = desconto;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }




}


