package entidades;
// Generated 04/06/2018 13:52:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private Integer idFornecedor;
     private Usuario usuario;
     private String nome;
     private String cnpj;
     private String endereco;
     private Set compras = new HashSet(0);
     private Set produtos = new HashSet(0);

    public Fornecedor() {
    }

    public Fornecedor(Usuario usuario, String nome, String cnpj, String endereco, Set compras, Set produtos) {
       this.usuario = usuario;
       this.nome = nome;
       this.cnpj = cnpj;
       this.endereco = endereco;
       this.compras = compras;
       this.produtos = produtos;
    }
   
    public Integer getIdFornecedor() {
        return this.idFornecedor;
    }
    
    public void setIdFornecedor(Integer idFornecedor) {
        this.idFornecedor = idFornecedor;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }


public String toString() {
        return nome;
    }

}


