package entidades;
// Generated 04/06/2018 13:52:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nome;
     private String login;
     private String senha;
     private Set compras = new HashSet(0);
     private Set produtos = new HashSet(0);
     private Set fornecedors = new HashSet(0);
     private Set clientes = new HashSet(0);
     private Set vendas = new HashSet(0);

    public Usuario() {
    }

    public Usuario(String nome, String login, String senha, Set compras, Set produtos, Set fornecedors, Set clientes, Set vendas) {
       this.nome = nome;
       this.login = login;
       this.senha = senha;
       this.compras = compras;
       this.produtos = produtos;
       this.fornecedors = fornecedors;
       this.clientes = clientes;
       this.vendas = vendas;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }
    public Set getFornecedors() {
        return this.fornecedors;
    }
    
    public void setFornecedors(Set fornecedors) {
        this.fornecedors = fornecedors;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


