package entidades;
// Generated 04/06/2018 13:52:03 by Hibernate Tools 4.3.1



/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private Integer idVenda;
     private Cliente cliente;
     private Produto produto;
     private Usuario usuario;
     private Double precoUnitario;
     private Integer quantidade;
     private Double desconto;
     private Double total;

    public Venda() {
    }

    public Venda(Cliente cliente, Produto produto, Usuario usuario, Double precoUnitario, Integer quantidade, Double desconto, Double total) {
       this.cliente = cliente;
       this.produto = produto;
       this.usuario = usuario;
       this.precoUnitario = precoUnitario;
       this.quantidade = quantidade;
       this.desconto = desconto;
       this.total = total;
    }
   
    public Integer getIdVenda() {
        return this.idVenda;
    }
    
    public void setIdVenda(Integer idVenda) {
        this.idVenda = idVenda;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Double getPrecoUnitario() {
        return this.precoUnitario;
    }
    
    public void setPrecoUnitario(Double precoUnitario) {
        this.precoUnitario = precoUnitario;
    }
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }
    public Double getDesconto() {
        return this.desconto;
    }
    
    public void setDesconto(Double desconto) {
        this.desconto = desconto;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }




}


